stages:
  - test
  - deploy

UnitTestLab1:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  when: on_success
  script:
    - python manage.py test lab_1

Lab1Deploy:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --api-key=HEROKU_APIKEY --app=$HEROKU_APP_NAME
  environment:
    name: production
    url: $HEROKU_APP_HOST
  when: manual
